{% set name = "pytest-json-report" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d5efbd90133568eb57bf8c72e8ee418aadc467c38f6144f23395ebcfd1c3c2d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pytest >=4.2.0
    - pytest-metadata
    - python

test:
  imports:
    - pytest_jsonreport

about:
  home: https://pypi.org/project/pytest-json-report/
  summary: A pytest plugin to report test results as JSON files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
